### ISSUE TITLE
App crashes when taking photo

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-Android#81]
Device - Nexus 6, Android Version 23

ForestDB+Encyrption 1.3.1-27

Steps to reproduce:
- Create List
- Create Task
- Take photo
- App Crashes

This may not happen everytime.

**Comment by pasin** [comment]
```
com.couchbase.todolite E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.couchbase.todolite, PID: 20448
                                                                        java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent {  }} to activity {com.couchbase.todolite/com.couchbase.todolite.TaskActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                            at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                            at java.io.File.fixSlashes(File.java:183)
                                                                            at java.io.File.<init>(File.java:130)
                                                                            at com.couchbase.todolite.TaskActivity.onActivityResult(TaskActivity.java:413)
                                                                            at android.app.Activity.dispatchActivityResult(Activity.java:6456)
                                                                            at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                                            at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by worker886** [comment]
using ACTION_IMAGE_CAPTURE makes TaskActivity restart so that mDatabase in TaskActivity  is null.
