### ISSUE TITLE
Unable to login with facebook

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-Android#82]
Using Nexus 5 - Android 6.0.1 - CBL Android 1.3.1-28

Steps to repo:
- deploy todolite
- try to login with facebook
- login modal fails to push

I am seeing the following error in the logs

```
08-31 16:39:23.819 1192-1192/? I/Keyboard.Facilitator: onFinishInput()
08-31 16:39:23.822 20724-20724/? E/ToDoLite: Facebook login error
                                             net::ERR_NAME_NOT_RESOLVED
                                                 at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:190)
                                                 at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:159)
                                                 at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
                                                 at com.couchbase.todolite.LoginActivity.onActivityResult(LoginActivity.java:78)
                                                 at android.app.Activity.dispatchActivityResult(Activity.java:6456)
                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                 at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:148)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-31 16:39:23.824 20724-20724/? W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 20724
08-31 16:39:26.822 198-808/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
```

**Comment by sethrosetter** [comment]
This was my issue. I wasn't connected to a network on my device.
